---
sidebar: sidebar 
permalink: solutions/bac-overview.html 
keywords: bluexp automation catalog, automation catalog, overview, introduction 
summary: Le catalogue d’automatisation de la console NetApp est une collection de solutions d’automatisation disponibles pour les clients, partenaires et employés de NetApp .  Le catalogue présente plusieurs fonctionnalités et avantages. 
---
= Présentation du catalogue d'automatisation de la console NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le catalogue d’automatisation de la console NetApp est une collection de solutions d’automatisation disponibles pour les clients, partenaires et employés de NetApp .  Le catalogue présente plusieurs fonctionnalités et avantages.

Un seul emplacement pour vos besoins d'automatisation:: Vous pouvez accéder au https://console.netapp.com/automationCatalog["Catalogue d'automatisation de la console NetApp"^] via l'interface utilisateur Web de la console.  Cela fournit un emplacement unique pour les scripts, les playbooks et les modules nécessaires pour améliorer l'automatisation et le fonctionnement de vos produits et services NetApp .
Les solutions sont créées et testées par NetApp:: Toutes les solutions d'automatisation et tous les scripts ont été créés et testés par NetApp. Chaque solution cible une demande ou un cas d'utilisation spécifique. La priorité est donnée à l'intégration avec les services de fichiers et de données NetApp.
Documentation:: Chacune des solutions d’automatisation comprend une documentation associée pour vous aider à démarrer.  Bien que les solutions soient accessibles via l'interface Web de la console, toute la documentation est disponible sur ce site.  La documentation est organisée en fonction des produits NetApp et des services cloud.
Une base solide pour l'avenir:: NetApp s'engage à aider ses clients à améliorer et à rationaliser l'automatisation de leurs centres de données et de leurs environnements cloud.  Nous prévoyons de continuer à améliorer le catalogue d’automatisation de la console pour répondre aux exigences des clients, aux changements technologiques et à l’intégration continue des produits.
Votre avis nous intéresse:: L'équipe d'automatisation du service d'expérience client (CXO) de NetApp voudrait vous entendre. Si vous avez des commentaires, des problèmes ou des demandes concernant des fonctionnalités, veuillez envoyer un e-mail à mailto:ng-cxo-automation-admins@NetApp.com[équipe d'automatisation CXO].

