---
sidebar: sidebar 
permalink: api/netapp-console.html 
keywords: netapp products, product api, rest, rest api, bluexp, bluexp control plane, netapp, console 
summary: 'NetApp Console est un plan de contrôle unifié qui fournit une plate-forme multicloud hybride pour l"administration des services de stockage et de données dans les environnements sur site et dans le cloud public. Il est composé de plusieurs services ou composants distincts, chacun exposant une API REST associée.  Consultez la documentation et les ressources associées fournies ci-dessous pour commencer à automatiser votre environnement dans la console à l’aide des API REST de la console.' 
---
= Plan de contrôle de la console NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console est un plan de contrôle unifié qui fournit une plate-forme multicloud hybride pour l'administration des services de stockage et de données dans les environnements sur site et dans le cloud public. Il est composé de plusieurs services ou composants distincts, chacun exposant une API REST associée.  Consultez la documentation et les ressources associées fournies ci-dessous pour commencer à automatiser votre environnement dans la console à l’aide des API REST de la console.

.API REST de la console NetApp
Vous pouvez utiliser les différentes API REST pour automatiser l'administration de vos services de stockage et de données gérés par la console.

* https://docs.netapp.com/us-en/console-automation/["Documentation de l'API de la console NetApp"^]


.Famille de consoles NetApp
La documentation de la famille Console comprend tout ce dont vous avez besoin pour commencer à utiliser le plan de contrôle de la console.

* https://docs.netapp.com/us-en/console-family/["Documentation de la console NetApp"^]

